### ISSUE TITLE
Can't build from sources

### ISSUE THREAD

**Issue by nestquik** [AnakinSklavenwalker/ModernApplicationFramework#1]
A large number of errors occur during build. @AnakinSklavenwalker, could you check the files in the repository? It seems to me that not all the files are uploaded.

**Comment by AnakinSklavenwalker** [comment]
so i just pushed my recent commits online and downloaded the repo as zip and tried to compile it. 
No errors. I recommend choosing as executable Project: ModernApplicationFramework.MVVM.Demo

VS2017 + Resharper used

**Comment by nestquik** [comment]
Seems like I can build Modern Application Framework.MVVM.Demo, but there's still some trouble in few files for example:
![image](https://user-images.githubusercontent.com/10574210/30236817-922e1c4c-952b-11e7-836a-6cc61ae1b4a3.png)
Here is the full list of files with issues:
![image](https://user-images.githubusercontent.com/10574210/30236835-d67bc930-952b-11e7-9ae0-61506c48978f.png)

**Comment by AnakinSklavenwalker** [comment]
yes this is because the assembly maf.MVVM is not used any more and will be deleted when code merging and other stuff is done. apologize for that confusing structure it has at the moment

**Comment by nestquik** [comment]
Oh, ok, that’s confusing.

**Comment by nestquik** [comment]
It's seems that MAF is more "natural" and close to VS-style than gemini. I'm going to use it in my project, so give me to know if u going to fix this is close-time. Thanks.

**Comment by AnakinSklavenwalker** [comment]
this is a free time project I'm developing from time to time. at the moment I can only do work a few hours a week on it. Thanks for your interest though ;)

**Comment by nestquik** [comment]
@AnakinSklavenwalker if u have some tasks - feel free to share, I will do my best to help.

**Comment by nestquik** [comment]
It seems that this issue is no longer necessary 👍
