### ISSUE TITLE
Default gesture collection is not initialized

### ISSUE THREAD

**Issue by nestquik** [AnakinSklavenwalker/ModernApplicationFramework#10]
I think `GestureService` method `LoadDefaultGestures` should be called after `Initialize` in `KeyboardGestureServicesModule`, I've just tried it and it works.

**Comment by AnakinSklavenwalker** [comment]
currently i'm working on the key gesture stuff. there are many issues and maybe even crashes.

**Comment by AnakinSklavenwalker** [comment]
Removed the module approach as modules must be independent from each other and the `KeyBindings `are too low level. `KeyBindingManager `will apply default gestures by application settings of hardcoded values.
