### ISSUE TITLE
Structuring the solution

### ISSUE THREAD

**Issue by nestquik** [AnakinSklavenwalker/ModernApplicationFramework#14]
It seems a little strange to me that solution contains empty and obsolete projects.
I think it's good practice to put tests and source code in different folders, as it done in dotnet projects. for example [dotnet/BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet).
Talking about modules - as for me they should be in projects with "Extensibility" suffix.

**Comment by AnakinSklavenwalker** [comment]
The Framework is pre alpha. of course there is some garbage in terms of projects etc. I don't want to delete them (yet) as they might contain code i'll use later or the will be used in the future. 

puttings tests in different folder sounds ok for me. as i don't have that many tests i thought this was obsolete. 

About modules I'm not sure how I want to structure them in the future. but i don't quiet like the suffix you suggest much.

**Comment by nestquik** [comment]
Resolved due https://github.com/AnakinSklavenwalker/ModernApplicationFramework/commit/88393464a054b96efa39c95d6a470d8d6ca34051](commit)
