### ISSUE TITLE
Get rid of using IoC as ServiceLocator

### ISSUE THREAD

**Issue by nestquik** [AnakinSklavenwalker/ModernApplicationFramework#15]
The things like `IoC.Get<IApplicationEnvironment>().Setup();` in `OnStartup` method of bootstrapper sound to me like task for event aggregator.
Maybe we should think about architecture?

**Comment by AnakinSklavenwalker** [comment]
Are there any more advantages instead of the looks of the code. If not there is no need to change it as it works as it is now.

**Comment by nestquik** [comment]
If we going to test system in future with mocks it would be very hard to maintain.
