### ISSUE TITLE
Code review issues

### ISSUE THREAD

**Issue by nestquik** [AnakinSklavenwalker/ModernApplicationFramework#16]
https://github.com/AnakinSklavenwalker/ModernApplicationFramework/blob/a51a452c2a1e220ba209cead1d7266b4ba52161a/ModernApplicationFramework/Basics/Services/Bootstrapper.cs#L91
Does this thing should be in framework code? It looks more specific to the user.

**Comment by nestquik** [comment]
https://github.com/AnakinSklavenwalker/ModernApplicationFramework/blob/d738ab1a41754665779e633e7de618891bb9a9a5/ModernApplicationFramework.Extended/ExtendedBootstrapper.cs#L31
Seems like double-registering, cuz it's already registered in base bootstrapper:
https://github.com/AnakinSklavenwalker/ModernApplicationFramework/blob/a51a452c2a1e220ba209cead1d7266b4ba52161a/ModernApplicationFramework/Basics/Services/Bootstrapper.cs#L78

**Comment by nestquik** [comment]
https://github.com/AnakinSklavenwalker/ModernApplicationFramework/blob/d738ab1a41754665779e633e7de618891bb9a9a5/ModernApplicationFramework.Extended/ExtendedBootstrapper.cs#L39-L56
This overrides the same base class function and simply ignores exception, which seems odd, cuz u can't use application when there're exists some DI-errors...

**Comment by nestquik** [comment]
https://github.com/AnakinSklavenwalker/ModernApplicationFramework/blob/d738ab1a41754665779e633e7de618891bb9a9a5/ModernApplicationFramework.Extended/ExtendedBootstrapper.cs#L34-L37
This should be in base class.

**Comment by nestquik** [comment]
https://github.com/AnakinSklavenwalker/ModernApplicationFramework/blob/a51a452c2a1e220ba209cead1d7266b4ba52161a/ModernApplicationFramework/Basics/Services/Bootstrapper.cs#L48

This thing is not necessary, we don't need priority at all, in `CommandRouter` we can just check if comand hanbler assembly is the same as execution assembly.

**Comment by nestquik** [comment]
I'm just dived in bootstrappers and seems very odd to have `Bootstrapper` which isn't showing any view and `ExtendedBootstrapper`

**Comment by AnakinSklavenwalker** [comment]
#1 There is a reason this code exists and I won't remove it. Of course this is a "user side issue" but as users are usually not aware of some things i'd like to handle it by the framework,

#2 Again. The project is in pre alpha. 

#3 i agree

#4 as it does not break anything i'd rather have it in code. i'm not fully sure if it does not crash anything if it gets removed.

#5 MAF is a core framework. it only should offer a code base. Any dev using it has the option to compile it's own feature set. MAF.Extended is focused on developing VS-like UI applications. Therefore plain MAF Bootstrapper does not do that handling MEF while ExtendedBootsrapper has some application presets like showing a view

**Comment by AnakinSklavenwalker** [comment]
2) Odd Try catch throw removed

**Comment by nestquik** [comment]
If we stick to the logic of the Caliburn Micro then bootstrappers must be abstract and the initialization method must be called in the bootstrapper of the client application.

**Comment by AnakinSklavenwalker** [comment]
If you could provide a pull request for that that would be great because i'm not quiet sure what you mean

**Comment by nestquik** [comment]
Resolved.
