### ISSUE TITLE
Just a question about some code in DockingManager

### ISSUE THREAD

**Issue by nestquik** [AnakinSklavenwalker/ModernApplicationFramework#24]
https://github.com/AnakinSklavenwalker/ModernApplicationFramework/blob/d17b4be099f06d941af8988e32d5885706b4d986/src/ModernApplicationFramework/Docking/DockingManager.cs#L1281-L1287

Seems like it should be done in this way?
```
if (_logicalChildren.Select(ch => ch.GetValueOrDefault<object>()).Contains(element))
{
#if !DEBUG
    return;
#else
    throw new InvalidOperationException();
#endif
}
```

**Comment by AnakinSklavenwalker** [comment]
this is original code from Xceed, so i don't know their intentions
