### ISSUE TITLE
Error with latest commits

### ISSUE THREAD

**Issue by nestquik** [AnakinSklavenwalker/ModernApplicationFramework#25]
Few latest commits with infobars break something.
When I'm attaching (via drag & drop) tool window to document area I got an unhandled exception of type 'System.ArgumentException' occurred in WindowsBase.dll - `Must disconnect specified child from current parent Visual before attaching to new parent Visual.` It was ok in 2854fa2ec866adcbb18eecb56ba2df15193ca595

**Comment by AnakinSklavenwalker** [comment]
Fixed with [790a5e0](https://github.com/AnakinSklavenwalker/ModernApplicationFramework/commit/790a5e0400bdcc586403dba6af6b94f9b9e06777)
