### ISSUE TITLE
Toggle commands

### ISSUE THREAD

**Issue by nestquik** [AnakinSklavenwalker/ModernApplicationFramework#27]
Is there any commands in framework with ability to toggle on value? For example pin tab.
![image](https://user-images.githubusercontent.com/10574210/32697483-ce44744c-c799-11e7-8148-43188d66870d.png)

**Comment by AnakinSklavenwalker** [comment]
I'm not quiet sure which pinning you mean. there is document pinning and there is tool window pinning. 
Also please tell me what you mean with:
> toggle on value?

**Comment by nestquik** [comment]
Take a look on screenshot, it’s a standard behavior of pinning document in VS (the icon is within blue rectangle when pinned)
