### ISSUE TITLE
Error in Inspector module

### ISSUE THREAD

**Issue by nestquik** [AnakinSklavenwalker/ModernApplicationFramework#8]
When the inspected property doesn't have a setter, the control associated with the inspector must be disabled. An example is - SampleViewModel. Also, it's seems like simple Inspectors such as int, or double can't convert data from string to type they associated.

**Comment by AnakinSklavenwalker** [comment]
I haven't looked at external modules like inspector and output yet. The core framework still is not ready. Consider this whole framework as pre-alpha.
